# Generated by Django 2.2.3 on 2019-08-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='payment_type',
            field=models.CharField(default='other', max_length=100),
        ),
    ]
